# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agritrade', '0003_crop_phones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('Farmer_Name', models.CharField(max_length=50)),
                ('farmer_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('pincode', models.IntegerField()),
                ('phone', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='agritrade.Phones')),
            ],
        ),
    ]
