# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agritrade', '0005_auto_20161018_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('order_ammount', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('rate', models.BigIntegerField(default=None)),
                ('status', models.CharField(max_length=200)),
                ('order_date', models.DateField()),
                ('desc', models.TextField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='crop',
            name='price',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agritrade.Phones'),
        ),
        migrations.AlterField(
            model_name='phones',
            name='id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='agritrade.Customer'),
        ),
        migrations.AddField(
            model_name='crop_order',
            name='crop_for_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agritrade.Crop'),
        ),
        migrations.AddField(
            model_name='crop_order',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agritrade.Customer'),
        ),
        migrations.AddField(
            model_name='crop_order',
            name='farmer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agritrade.Farmer'),
        ),
    ]
