# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agritrade', '0006_auto_20161018_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='phones',
            name='phone_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='phones',
            name='id',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='agritrade.Customer'),
        ),
    ]
