# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agritrade', '0010_auto_20161018_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='Precaution',
            field=models.CharField(default='A default Precaution', max_length=50),
        ),
    ]
