# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agritrade', '0011_auto_20161018_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop_order',
            name='status',
            field=models.CharField(choices=[('A', 'Available'), ('NA', 'Not Available')], max_length=200),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(choices=[(1, 'Admin'), (2, 'Agricultural Officer'), (3, 'Agent')], max_length=200),
        ),
    ]
