# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agritrade', '0012_auto_20161018_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='Access_level',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')]),
        ),
    ]
