# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agritrade', '0013_auto_20161018_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('buyer_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=50)),
                ('country', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Buyer_Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(max_length=450)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer_Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agritrade.Comments')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('Reg_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agritrade.Comments')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Quantity_In', models.IntegerField()),
                ('Quantity_Out', models.IntegerField()),
                ('Rent', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='farmer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='farmer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agritrade.Farmer'),
        ),
        migrations.AddField(
            model_name='store',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agritrade.Staff'),
        ),
        migrations.AddField(
            model_name='staff_comments',
            name='Staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agritrade.Staff'),
        ),
        migrations.AddField(
            model_name='registration',
            name='farmer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agritrade.Farmer'),
        ),
        migrations.AddField(
            model_name='farmer_comments',
            name='farmer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agritrade.Farmer'),
        ),
        migrations.AddField(
            model_name='buyer_comments',
            name='B_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agritrade.Comments'),
        ),
        migrations.AddField(
            model_name='buyer_comments',
            name='Buyer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agritrade.Buyer'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='farmer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agritrade.Farmer'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agritrade.Phones'),
        ),
        migrations.AddField(
            model_name='admin_comments',
            name='A_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agritrade.Comments'),
        ),
        migrations.AddField(
            model_name='admin_comments',
            name='admin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agritrade.Staff'),
        ),
    ]
