# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agritrade', '0014_auto_20161018_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='crop_Quantity_left',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Remaining', models.IntegerField()),
                ('crop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agritrade.Crop')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agritrade.Store')),
            ],
        ),
        migrations.CreateModel(
            name='Crop_Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Crop_supply_id', models.IntegerField(default=None)),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agritrade.Farmer')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agritrade.Store')),
            ],
        ),
        migrations.CreateModel(
            name='Farmer_Plantation',
            fields=[
                ('plantation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('crop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agritrade.Crop')),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agritrade.Farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField(default=None)),
                ('Balance', models.IntegerField(default=None)),
                ('Total', models.IntegerField(default=None)),
                ('Order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agritrade.Crop_order')),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agritrade.Buyer')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agritrade.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Season_Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Season', models.CharField(choices=[('SNY', 'Sunny'), ('WTR', 'Winter'), ('RNY', 'Rainy'), ('SPR', 'Spring')], max_length=50)),
                ('Unique_id', models.IntegerField()),
                ('crop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agritrade.Crop')),
            ],
        ),
        migrations.CreateModel(
            name='Store_Crop',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('crop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agritrade.Crop')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agritrade.Store')),
            ],
        ),
    ]
