# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agritrade', '0015_crop_quantity_left_crop_supply_farmer_plantation_order_process_season_crop_store_crop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season_crop',
            name='id',
        ),
        migrations.AlterField(
            model_name='season_crop',
            name='Unique_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
