# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agritrade', '0017_auto_20161018_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'Agricultural Officer'), ('3', 'Agent')], max_length=200),
        ),
    ]
