# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agritrade', '0018_auto_20161018_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='Irrigation',
            field=models.BooleanField(verbose_name='Irrigation'),
        ),
    ]
