# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agritrade', '0019_auto_20161018_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('date_of_birth', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('type_of', models.CharField(choices=[('Farmer', 'Farmer'), ('Buyer', 'Buyer'), ('Staff', 'Staff'), ('Officer', 'Offiicer')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
