# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agritrade', '0024_auto_20161019_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='buyer_id',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='agritrade.Customer'),
        ),
    ]
