# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agritrade', '0025_auto_20161019_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='Date of Birth',
            new_name='dob',
        ),
    ]
