# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agritrade', '0026_auto_20161020_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='photograph',
            field=models.ImageField(upload_to='C:\\DBMS'),
        ),
    ]
