# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agritrade', '0028_auto_20161105_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='Soil_health',
            field=models.CharField(choices=[('1', 'Excellent'), ('2', 'Very Good'), ('3', 'Good'), ('4', 'Satisfactory'), ('5', 'Bad')], max_length=50),
        ),
    ]
