# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agritrade', '0030_auto_20161106_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='name',
            field=models.TextField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(default=None, verbose_name='Contact No'),
        ),
    ]
