# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agritrade', '0031_auto_20161107_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='User_id',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.CharField(default=None, max_length=25),
        ),
    ]
