# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agritrade', '0036_auto_20161107_0133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop_order',
            old_name='crop_for_sale',
            new_name='Crop',
        ),
    ]
