# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agritrade', '0037_auto_20161107_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop_order',
            name='Crop',
        ),
    ]
