# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agritrade', '0038_remove_crop_order_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop_order',
            name='crop_for_sale',
            field=models.ManyToManyField(to='agritrade.Crop'),
        ),
    ]
