# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agritrade', '0039_crop_order_crop_for_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='photograph',
            field=models.ImageField(null=True, upload_to='C:\\DBMS'),
        ),
    ]
