# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agritrade', '0040_auto_20161107_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer',
            options={'verbose_name': 'Only Buyers', 'verbose_name_plural': 'Only Buyers'},
        ),
        migrations.AlterModelOptions(
            name='buyer_phones',
            options={'verbose_name': 'Buyer Contact Details', 'verbose_name_plural': 'Buyer Contact Details'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'All Comments ', 'verbose_name_plural': 'All Comments'},
        ),
        migrations.AlterModelOptions(
            name='crop',
            options={'verbose_name': 'Crop Detail', 'verbose_name_plural': 'Crop Details'},
        ),
        migrations.AlterModelOptions(
            name='crop_order',
            options={'verbose_name': 'Customer Order Details', 'verbose_name_plural': 'Customer Order Details'},
        ),
        migrations.AlterModelOptions(
            name='crop_quantity_left',
            options={'verbose_name': 'Quantity left per Crop', 'verbose_name_plural': 'Quantity left per Crop'},
        ),
        migrations.AlterModelOptions(
            name='crop_supply',
            options={'verbose_name': 'Crop Supply', 'verbose_name_plural': 'Crop Supply'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Registered Customer Details', 'verbose_name_plural': 'Registerd Customers Details '},
        ),
        migrations.AlterModelOptions(
            name='farmer',
            options={'verbose_name': 'Registered Farmer Details', 'verbose_name_plural': 'Registered Farmer Details'},
        ),
        migrations.AlterModelOptions(
            name='farmer_phones',
            options={'verbose_name': 'Farmer Contact Details', 'verbose_name_plural': 'Farmer Contact Details'},
        ),
        migrations.AlterModelOptions(
            name='farmer_plantation',
            options={'verbose_name': 'Farmer Plantation', 'verbose_name_plural': 'Farmer Plantation'},
        ),
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'User Information', 'verbose_name_plural': 'User Information'},
        ),
        migrations.AlterModelOptions(
            name='order_process',
            options={'verbose_name': 'Order Reports', 'verbose_name_plural': 'Order Reports'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'Registered Users', 'verbose_name_plural': 'Registered Users'},
        ),
        migrations.AlterModelOptions(
            name='season_crop',
            options={'verbose_name': 'Crops Based on Season', 'verbose_name_plural': 'Crops Based on Seasons'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Staff Details', 'verbose_name_plural': 'Staff Details'},
        ),
        migrations.AlterModelOptions(
            name='staff_phones',
            options={'verbose_name': 'Staff Contact Details', 'verbose_name_plural': 'Staff Contact Details'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Store Details', 'verbose_name_plural': 'Store Details'},
        ),
        migrations.AlterModelOptions(
            name='store_crop',
            options={'verbose_name': 'Available Crops in Stores', 'verbose_name_plural': 'Available Crops in Stores'},
        ),
    ]
