# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agritrade', '0041_auto_20161109_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Phones',
            fields=[
                ('phone_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('phone', models.BigIntegerField(default=None)),
            ],
            options={
                'verbose_name_plural': 'Customer Contact Details',
                'verbose_name': 'Customer Contacts',
            },
        ),
        migrations.AlterModelOptions(
            name='buyer_phones',
            options={'verbose_name': 'Buyer Contacts', 'verbose_name_plural': 'Buyer Contact Details'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'New Comment', 'verbose_name_plural': 'All Comments'},
        ),
        migrations.AlterModelOptions(
            name='crop',
            options={'verbose_name': 'Crop', 'verbose_name_plural': 'Crop Details'},
        ),
        migrations.AlterModelOptions(
            name='crop_order',
            options={'verbose_name': 'New Crop Order', 'verbose_name_plural': 'Customer Order Details'},
        ),
        migrations.AlterModelOptions(
            name='crop_quantity_left',
            options={'verbose_name': 'Update Stock', 'verbose_name_plural': 'Quantity left per Crop'},
        ),
        migrations.AlterModelOptions(
            name='crop_supply',
            options={'verbose_name': 'Crop Supply', 'verbose_name_plural': 'Crop Supplies'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Register New Customer', 'verbose_name_plural': 'Registerd Customers Details '},
        ),
        migrations.AlterModelOptions(
            name='farmer',
            options={'verbose_name': 'Register Farmer', 'verbose_name_plural': 'Registered Farmer Details'},
        ),
        migrations.AlterModelOptions(
            name='farmer_phones',
            options={'verbose_name': 'Farmer Detail', 'verbose_name_plural': 'Farmer Contact Details'},
        ),
        migrations.AlterModelOptions(
            name='farmer_plantation',
            options={'verbose_name': 'Farmer Plantation', 'verbose_name_plural': 'Farmer Plantations'},
        ),
        migrations.AlterModelOptions(
            name='order_process',
            options={'verbose_name': 'Order Process', 'verbose_name_plural': 'Order Reports'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'New Registrations', 'verbose_name_plural': 'Registered Users'},
        ),
        migrations.AlterModelOptions(
            name='season_crop',
            options={'verbose_name': 'Additional Info to Crop', 'verbose_name_plural': 'Crops Based on Seasons'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Staff', 'verbose_name_plural': 'Staff Details'},
        ),
        migrations.AlterModelOptions(
            name='staff_phones',
            options={'verbose_name': 'Staff Contacts', 'verbose_name_plural': 'Staff Contact Details'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Store', 'verbose_name_plural': 'Store Details'},
        ),
        migrations.AlterModelOptions(
            name='store_crop',
            options={'verbose_name': 'Crop to Store', 'verbose_name_plural': 'Available Crops in Stores'},
        ),
        migrations.AddField(
            model_name='customer_phones',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agritrade.Customer'),
        ),
    ]
